### ISSUE TITLE
Verschwinden des Textes im GebauteGebäudeMenü

### ISSUE THREAD

**Issue by Erdragh** [MArkus44/OnlyTowns#1]
Wenn man im Menü, das die gebauten Gebäude anzeigt, auf die Seite klickt, circa bei der (nicht tatsächlich existierenden) scrollbar, dann schließt sich der Text, der in einem eigenen PopUp Menü zu sein scheint, aber nicht das Menü selbst.

**Comment by MArkus44** [comment]
gelöst
